package com.zwendo.restrikt.annotation

/**
 * This annotation is used to mark generated annotations, in order to discourage their use except for reflection
 * purposes.
 */
@RequiresOptIn(
    level = RequiresOptIn.Level.WARNING,
    message = """This element is generated by the Restrikt plugin. It is not intended to be used directly.
        To generate this element, use its corresponding annotation. You can freely opt-in for this element if you intend
        to use it through reflection.""",
)
@Target(AnnotationTarget.ANNOTATION_CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class RestriktGeneratedAnnotation
